namespace hues.Game
{
    public struct HuesImage
    {
        public readonly string TexturePath;
        public readonly string Name;

        public HuesImage(string path, string name)
        {
            TexturePath = path;
            Name = name;
        }

        public static HuesImage[] All = new HuesImage[]
        {
            new HuesImage("Agiri", "Agiri Goshiki"),
            new HuesImage("Ai", "Ai Enma"),
            new HuesImage("Akarin", "Akari Akaza"),
            new HuesImage("Akatsuki", "Akatsuki"),
            new HuesImage("Alice", "Alice Margatroid"),
            new HuesImage("Astraea", "Astraea"),
            new HuesImage("Asuha", "Asuha Touhara"),
            new HuesImage("Asuka", "Asuka Langley Soryu"),
            new HuesImage("Ayase", "Ayase Aragaki"),
            new HuesImage("CC", "C.C."),
            new HuesImage("Chika", "Chika Itou"),
            new HuesImage("Chiri", "Chiri Kitsu"),
            new HuesImage("Chitanda", "Eru Chitanda"),
            new HuesImage("Chiyo", "Chiyo Mihama"),
            new HuesImage("Cirno", "Cirno"),
            new HuesImage("Crona", "Crona"),
            new HuesImage("Demon Sisters", "Kneesocks Demon & Scanty Demon"),
            new HuesImage("Emi", "Emi Ibarazaki"),
            new HuesImage("Etna", "Etna"),
            new HuesImage("Eureka", "Eureka"),
            new HuesImage("Excel", "Excel"),
            new HuesImage("Faye", "Faye Valentine"),
            new HuesImage("Felli", "Felli Loss"),
            new HuesImage("Flandre", "Flandre Scarlet"),
            new HuesImage("Fran", "Fran Madaraki"),
            new HuesImage("Fuu", "Fuu Kasumi"),
            new HuesImage("Galil", "Galil AR"),
            new HuesImage("Hajime Ichinose", "Hajime Ichinose"),
            new HuesImage("Hakase", "Hakase Shinonome"),
            new HuesImage("Hanako", "Hanako Ikezawa"),
            new HuesImage("Haruhi Fujioka", "Haruhi Fujioka"),
            new HuesImage("Haruhi", "Haruhi Suzumiya"),
            new HuesImage("Haruko", "Haruko Haruhara"),
            new HuesImage("Hitoha", "Hitoha Marui"),
            new HuesImage("Holo", "Holo \"Wisewolf of Yoitsu\""),
            new HuesImage("Homura", "Homura Akemi"),
            new HuesImage("Hyatt", "Hyatt"),
            new HuesImage("Ibara", "Mayaka Ibara"),
            new HuesImage("Ika", "Ika Musume"),
            new HuesImage("Kagami", "Kagami Hiiragi"),
            new HuesImage("Kanade", "Kanade Tachibana"),
            new HuesImage("Kanoe", "Yuuko Kanoe"),
            new HuesImage("Kaori", "Kaori"),
            new HuesImage("Karen", "Karen Kujou"),
            new HuesImage("Kasukabe", "You Kasukabe"),
            new HuesImage("Kate", "Kate"),
            new HuesImage("Kirino", "Kirino Kousaka"),
            new HuesImage("Kirisame Marisa", "Kirisame Marisa"),
            new HuesImage("Konata", "Konota Izumi"),
            new HuesImage("Kurisu", "Kurisu Makise"),
            new HuesImage("Kuroko", "Kuroko Shirai"),
            new HuesImage("Kyouka", "Kyouka Midarezaki"),
            new HuesImage("Kyouko Sakura", "Kyouko Sakura"),
            new HuesImage("Kyouko Toshinou", "Kyouko Toshinou"),
            new HuesImage("Kyubey", "Kyubey"),
            new HuesImage("Lain (still)", "Lain Iwakura"),
            new HuesImage("Lala-Ru", "Lala-Ru"),
            new HuesImage("Lilly", "Lilly Satou"),
            new HuesImage("Louise", "Louise Françoise Le Blanc de La Vallière"),
            new HuesImage("Lucchini", "Francesa Lucchini"),
            new HuesImage("Lucy", "Lucy"),
            new HuesImage("Madotsuki", "Madotsuki"),
            new HuesImage("Mai", "Mai Minakami"),
            new HuesImage("Maka", "Maka Albarn"),
            new HuesImage("Makimaki", "Makina Sakamaki"),
            new HuesImage("Makoto", "Makoto Kikuchi"),
            new HuesImage("Mami", "Mami Tomoe"),
            new HuesImage("Mao", "Mao Amatsuka"),
            new HuesImage("Mary", "Mary"),
            new HuesImage("Mashiro", "Mashiro Mitsumine"),
            new HuesImage("Mayoi", "Mayoi Hachikuji"),
            new HuesImage("Mayuri", "Mayuri Shiina"),
            new HuesImage("Megumi", "Airi Akizuki"),
            new HuesImage("Melfina", "Melfina"),
            new HuesImage("Mey-Rin", "Mey-Rin"),
            new HuesImage("Miho", "Miho"),
            new HuesImage("Miku", "Miku Hatsune"),
            new HuesImage("Mio Naganohara", "Mio Naganohara"),
            new HuesImage("Mio", "Mio Akiyama"),
            new HuesImage("Mirai", "Mirai Kuriyama"),
            new HuesImage("Misaka", "Mikoto Misaka"),
            new HuesImage("Misaki", "Misaki Nakahara"),
            new HuesImage("Miu", "Miu Matsuoka"),
            new HuesImage("Miyako", "Miyako"),
            new HuesImage("Mizuki", "Mizuki"),
            new HuesImage("Momo", "Momo Belia Deviluke"),
            new HuesImage("Monoko", "Monoko"),
            new HuesImage("Morgiana", "Morgiana"),
            new HuesImage("Motoko", "Motoko \"Major\" Kusanagi"),
            new HuesImage("Nano", "Nano Shinonome"),
            new HuesImage("Nee-san", "Iroe Genma"),
            new HuesImage("Noel", "Noël Kannagi"),
            new HuesImage("Nymph", "Nymph"),
            new HuesImage("Onihime", "Hime \"Onihime\" Onizuka"),
            new HuesImage("Osaka", "Ayumi \"Osaka\" Kasuga"),
            new HuesImage("Popura", "Popura Taneshima"),
            new HuesImage("Rei", "Rei Ayanami"),
            new HuesImage("Renge", "Renge Miyauchi"),
            new HuesImage("Rika", "Rika Furude"),
            new HuesImage("Rikka", "Rikka Takanashi"),
            new HuesImage("Rin Tezuka", "Rin Tezuka"),
            new HuesImage("Rin", "Rin Tohsaka"),
            new HuesImage("Ritsu", "Ritsu Tainaka"),
            new HuesImage("Ruri", "Ruri Gokou"),
            new HuesImage("Ryuuko", "Ryuuko Matoi"),
            new HuesImage("Sako", "Sako RK95"),
            new HuesImage("Sakura", "Sakura Kinomoto"),
            new HuesImage("Sakurako", "Sakura Ohmuro"),
            new HuesImage("Sanae", "Sanae Dekomori"),
            new HuesImage("Senjougahara", "Hitagi Senjougahara"),
            new HuesImage("Shiina", "Mashiro Shiina"),
            new HuesImage("Shinobu", "Shinobu Oshino"),
            new HuesImage("Sonya", "Sonya"),
            new HuesImage("Stocking", "Stocking Anarchy"),
            new HuesImage("Suiseiseki", "Suiseiseki"),
            new HuesImage("Taiga", "Taiga Aisaka"),
            new HuesImage("Tomoko", "Tomoko Kuroki"),
            new HuesImage("Tsumiki", "Tsumiki Miniwa"),
            new HuesImage("Urotsuki", "Urotsuki"),
            new HuesImage("Winry", "Winry Rockbell"),
            new HuesImage("Yasuna", "Yasuna Oribe"),
            new HuesImage("Yin", "Yin"),
            new HuesImage("Yoko", "Yoko Littner"),
            new HuesImage("Yotsuba", "Yotsuba Koiwai"),
            new HuesImage("Yui", "Yui Hirasawa"),
            new HuesImage("Yukari", "Yukari Hinata"),
            new HuesImage("Yuki", "Yuki Nagato"),
            new HuesImage("Yuno", "Yuno Gasai"),
            new HuesImage("Yunocchi", "Yuno"),
            new HuesImage("Yuuko", "Yuuno Aioi"),
        };
    }
}
