namespace hues.Game
{
    public struct Image
    {
        public string Name { get; init; }
        public string Source { get; init; }

        public string TexturePath { get; init; }

        public Respack Respack { get; init; }

        public Image(string path, string name)
        {
            TexturePath = path;
            Name = name;
            Source = null;
            Respack = null;
        }

        public static Image[] All = new Image[]
        {
            new Image("Agiri", "Agiri Goshiki"),
            new Image("Ai", "Ai Enma"),
            new Image("Akarin", "Akari Akaza"),
            new Image("Akatsuki", "Akatsuki"),
            new Image("Alice", "Alice Margatroid"),
            new Image("Astraea", "Astraea"),
            new Image("Asuha", "Asuha Touhara"),
            new Image("Asuka", "Asuka Langley Soryu"),
            new Image("Ayase", "Ayase Aragaki"),
            new Image("CC", "C.C."),
            new Image("Chika", "Chika Itou"),
            new Image("Chiri", "Chiri Kitsu"),
            new Image("Chitanda", "Eru Chitanda"),
            new Image("Chiyo", "Chiyo Mihama"),
            new Image("Cirno", "Cirno"),
            new Image("Crona", "Crona"),
            new Image("Demon Sisters", "Kneesocks Demon & Scanty Demon"),
            new Image("Emi", "Emi Ibarazaki"),
            new Image("Etna", "Etna"),
            new Image("Eureka", "Eureka"),
            new Image("Excel", "Excel"),
            new Image("Faye", "Faye Valentine"),
            new Image("Felli", "Felli Loss"),
            new Image("Flandre", "Flandre Scarlet"),
            new Image("Fran", "Fran Madaraki"),
            new Image("Fuu", "Fuu Kasumi"),
            new Image("Galil", "Galil AR"),
            new Image("Hajime Ichinose", "Hajime Ichinose"),
            new Image("Hakase", "Hakase Shinonome"),
            new Image("Hanako", "Hanako Ikezawa"),
            new Image("Haruhi Fujioka", "Haruhi Fujioka"),
            new Image("Haruhi", "Haruhi Suzumiya"),
            new Image("Haruko", "Haruko Haruhara"),
            new Image("Hitoha", "Hitoha Marui"),
            new Image("Holo", "Holo \"Wisewolf of Yoitsu\""),
            new Image("Homura", "Homura Akemi"),
            new Image("Hyatt", "Hyatt"),
            new Image("Ibara", "Mayaka Ibara"),
            new Image("Ika", "Ika Musume"),
            new Image("Kagami", "Kagami Hiiragi"),
            new Image("Kanade", "Kanade Tachibana"),
            new Image("Kanoe", "Yuuko Kanoe"),
            new Image("Kaori", "Kaori"),
            new Image("Karen", "Karen Kujou"),
            new Image("Kasukabe", "You Kasukabe"),
            new Image("Kate", "Kate"),
            new Image("Kirino", "Kirino Kousaka"),
            new Image("Kirisame Marisa", "Kirisame Marisa"),
            new Image("Konata", "Konota Izumi"),
            new Image("Kurisu", "Kurisu Makise"),
            new Image("Kuroko", "Kuroko Shirai"),
            new Image("Kyouka", "Kyouka Midarezaki"),
            new Image("Kyouko Sakura", "Kyouko Sakura"),
            new Image("Kyouko Toshinou", "Kyouko Toshinou"),
            new Image("Kyubey", "Kyubey"),
            new Image("Lain (still)", "Lain Iwakura"),
            new Image("Lala-Ru", "Lala-Ru"),
            new Image("Lilly", "Lilly Satou"),
            new Image("Louise", "Louise Françoise Le Blanc de La Vallière"),
            new Image("Lucchini", "Francesa Lucchini"),
            new Image("Lucy", "Lucy"),
            new Image("Madotsuki", "Madotsuki"),
            new Image("Mai", "Mai Minakami"),
            new Image("Maka", "Maka Albarn"),
            new Image("Makimaki", "Makina Sakamaki"),
            new Image("Makoto", "Makoto Kikuchi"),
            new Image("Mami", "Mami Tomoe"),
            new Image("Mao", "Mao Amatsuka"),
            new Image("Mary", "Mary"),
            new Image("Mashiro", "Mashiro Mitsumine"),
            new Image("Mayoi", "Mayoi Hachikuji"),
            new Image("Mayuri", "Mayuri Shiina"),
            new Image("Megumi", "Airi Akizuki"),
            new Image("Melfina", "Melfina"),
            new Image("Mey-Rin", "Mey-Rin"),
            new Image("Miho", "Miho"),
            new Image("Miku", "Miku Hatsune"),
            new Image("Mio Naganohara", "Mio Naganohara"),
            new Image("Mio", "Mio Akiyama"),
            new Image("Mirai", "Mirai Kuriyama"),
            new Image("Misaka", "Mikoto Misaka"),
            new Image("Misaki", "Misaki Nakahara"),
            new Image("Miu", "Miu Matsuoka"),
            new Image("Miyako", "Miyako"),
            new Image("Mizuki", "Mizuki"),
            new Image("Momo", "Momo Belia Deviluke"),
            new Image("Monoko", "Monoko"),
            new Image("Morgiana", "Morgiana"),
            new Image("Motoko", "Motoko \"Major\" Kusanagi"),
            new Image("Nano", "Nano Shinonome"),
            new Image("Nee-san", "Iroe Genma"),
            new Image("Noel", "Noël Kannagi"),
            new Image("Nymph", "Nymph"),
            new Image("Onihime", "Hime \"Onihime\" Onizuka"),
            new Image("Osaka", "Ayumi \"Osaka\" Kasuga"),
            new Image("Popura", "Popura Taneshima"),
            new Image("Rei", "Rei Ayanami"),
            new Image("Renge", "Renge Miyauchi"),
            new Image("Rika", "Rika Furude"),
            new Image("Rikka", "Rikka Takanashi"),
            new Image("Rin Tezuka", "Rin Tezuka"),
            new Image("Rin", "Rin Tohsaka"),
            new Image("Ritsu", "Ritsu Tainaka"),
            new Image("Ruri", "Ruri Gokou"),
            new Image("Ryuuko", "Ryuuko Matoi"),
            new Image("Sako", "Sako RK95"),
            new Image("Sakura", "Sakura Kinomoto"),
            new Image("Sakurako", "Sakura Ohmuro"),
            new Image("Sanae", "Sanae Dekomori"),
            new Image("Senjougahara", "Hitagi Senjougahara"),
            new Image("Shiina", "Mashiro Shiina"),
            new Image("Shinobu", "Shinobu Oshino"),
            new Image("Sonya", "Sonya"),
            new Image("Stocking", "Stocking Anarchy"),
            new Image("Suiseiseki", "Suiseiseki"),
            new Image("Taiga", "Taiga Aisaka"),
            new Image("Tomoko", "Tomoko Kuroki"),
            new Image("Tsumiki", "Tsumiki Miniwa"),
            new Image("Urotsuki", "Urotsuki"),
            new Image("Winry", "Winry Rockbell"),
            new Image("Yasuna", "Yasuna Oribe"),
            new Image("Yin", "Yin"),
            new Image("Yoko", "Yoko Littner"),
            new Image("Yotsuba", "Yotsuba Koiwai"),
            new Image("Yui", "Yui Hirasawa"),
            new Image("Yukari", "Yukari Hinata"),
            new Image("Yuki", "Yuki Nagato"),
            new Image("Yuno", "Yuno Gasai"),
            new Image("Yunocchi", "Yuno"),
            new Image("Yuuko", "Yuuno Aioi"),
        };
    }
}
