name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true

jobs:
  build:
    runs-on: ${{matrix.os.name}}

    strategy:
      matrix:
        os:
          - { name: ubuntu-latest, runtime: linux-x64  }
          - { name: windows-latest, runtime: win-x64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Publish
        run: dotnet publish hues.Desktop/ --configuration Release --runtime ${{matrix.os.runtime}} -p:Version=${{github.event.inputs.version}} --output hues.${{github.event.inputs.version}}.${{matrix.os.runtime}}

      # Have to tar the build output to preserve file permissions because artifact upload removes them :(
      - name: Tar Build Output
        shell: bash
        run: tar cvf ${{matrix.os.runtime}}-build.tar hues.${{github.event.inputs.version}}.${{matrix.os.runtime}}/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.os.runtime}}-build
          path: ${{matrix.os.runtime}}-build.tar

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Fetch Linux Build
        uses: actions/download-artifact@v2
        with:
          name: linux-x64-build

      - name: Untar Linux Build
        run: tar xvf linux-x64-build.tar

      - name: Compress Linux Build
        run: zip -r hues.${{github.event.inputs.version}}.linux-x64.zip hues.${{github.event.inputs.version}}.linux-x64/

      - name: Fetch Windows Build
        uses: actions/download-artifact@v2
        with:
          name: win-x64-build

      - name: Untar Windows Build
        run: tar xvf win-x64-build.tar

      - name: Compress Windows Build
        run: zip -r hues.${{github.event.inputs.version}}.win-x64.zip hues.${{github.event.inputs.version}}.win-x64/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.zip'
          tag_name: ${{github.event.inputs.version}}
          fail_on_unmatched_files: true
          body: This is a new release, patch notes haven't been added yet!
